# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import recipes_pb2 as recipes__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recipes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecipesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecipeWithURL = channel.unary_unary(
                '/recipes.RecipesService/GetRecipeWithURL',
                request_serializer=recipes__pb2.GetRecipeWithURLRequest.SerializeToString,
                response_deserializer=recipes__pb2.RecipeResponse.FromString,
                _registered_method=True)
        self.CreateRecipe = channel.unary_unary(
                '/recipes.RecipesService/CreateRecipe',
                request_serializer=recipes__pb2.CreateRecipeRequest.SerializeToString,
                response_deserializer=recipes__pb2.CreateRecipeResponse.FromString,
                _registered_method=True)


class RecipesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRecipeWithURL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRecipe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecipesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecipeWithURL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecipeWithURL,
                    request_deserializer=recipes__pb2.GetRecipeWithURLRequest.FromString,
                    response_serializer=recipes__pb2.RecipeResponse.SerializeToString,
            ),
            'CreateRecipe': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRecipe,
                    request_deserializer=recipes__pb2.CreateRecipeRequest.FromString,
                    response_serializer=recipes__pb2.CreateRecipeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recipes.RecipesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recipes.RecipesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecipesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRecipeWithURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recipes.RecipesService/GetRecipeWithURL',
            recipes__pb2.GetRecipeWithURLRequest.SerializeToString,
            recipes__pb2.RecipeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRecipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recipes.RecipesService/CreateRecipe',
            recipes__pb2.CreateRecipeRequest.SerializeToString,
            recipes__pb2.CreateRecipeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
