services:
  recipesdb:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - recipesdbvol:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  rmq:
    image: rabbitmq:3.13
    env_file: .env
  recipes:
    image: fenroe/molly-recipes:latest
    env_file: .env
    pull_policy: always
    depends_on:
      recipesdb:
        condition: service_healthy
  scraper:
    image: fenroe/molly-scraper:latest
    env_file: .env
    pull_policy: always
    depends_on:
      rmq:
        condition: service_started
  gateway:
    image: fenroe/molly-gateway:latest
    env_file: .env
    pull_policy: always
    depends_on:
      rmq:
        condition: service_started
      recipes:
        condition: service_started
      scraper:
        condition: service_started
  web:
    image: fenroe/molly-web:latest
    env_file: .env
    pull_policy: always
    ports:
      - 2000:3000
    depends_on:
      gateway:
        condition: service_started
volumes:
  recipesdbvol:
