// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Ingredient struct {
	ID         uuid.UUID
	RecipeID   uuid.UUID
	FullText   string
	IsOptional bool
	Name       string
	Quantity   string
	Unit       string
	Size       string
	Created    time.Time
}

type Instruction struct {
	ID       uuid.UUID
	RecipeID uuid.UUID
	Index    int32
	FullText string
	Created  time.Time
}

type Recipe struct {
	ID               uuid.UUID
	RecipeUrl        string
	Title            string
	Description      string
	CookingMethod    string
	Category         string
	ImageUrl         string
	PrepTimeMinutes  int32
	PrepTimeString   string
	CookTimeMinutes  int32
	CookTimeString   string
	TotalTimeMinutes int32
	TotalTimeString  string
	Created          time.Time
}

type Timer struct {
	ID            uuid.UUID
	InstructionID uuid.UUID
	Unit          string
	Value         int32
	Created       time.Time
}
