// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Ingredient struct {
	ID              uuid.UUID
	RecipeID        uuid.UUID
	FullText        string
	IsOptional      bool
	Name            string
	Quantity        float64
	QuantityString  string
	Unit            string
	Size            string
	IngredientGroup string
	Created         time.Time
}

type Instruction struct {
	ID       uuid.UUID
	RecipeID uuid.UUID
	Index    int32
	FullText string
	HasTimer bool
	Created  time.Time
}

type Recipe struct {
	ID               uuid.UUID
	RecipeUrl        string
	Title            string
	Description      string
	Cuisine          string
	CookingMethod    string
	Category         string
	ImageUrl         string
	Yields           string
	PrepTimeMinutes  int32
	CookTimeMinutes  int32
	TotalTimeMinutes int32
	Created          time.Time
}

type Timer struct {
	ID            uuid.UUID
	InstructionID uuid.UUID
	Unit          string
	Value         int32
	Created       time.Time
}
